<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <PlatformTarget>AnyCPU</PlatformTarget>
	<ApplicationIcon>Assets\favicon.ico</ApplicationIcon>
	<Platforms>AnyCPU</Platforms>

    <!-- Controls the company/app identity used by .NET user-scoped settings. -->
    <Company>Benchmark Sims</Company>
    <Product>Falcon BMS Launcher</Product>
    <AssemblyTitle>Falcon BMS Launcher</AssemblyTitle>
    <Description>Falcon BMS Launcher</Description>
  </PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)' == 'Debug'">
		<Version>3.0.0.9999</Version>
		<AssemblyVersion>3.0.0.9999</AssemblyVersion>
		<FileVersion>3.0.0.9999</FileVersion>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)' == 'Release'">
		<Version>3.0.0.0</Version>
		<AssemblyVersion>3.0.0.0</AssemblyVersion>
		<FileVersion>3.0.0.0</FileVersion>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
	  <PreferNativeArm64>True</PreferNativeArm64>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
	  <PreferNativeArm64>True</PreferNativeArm64>
	</PropertyGroup>

	<ItemGroup>
	  <None Remove="Assets\AVC.png" />
	  <None Remove="Assets\bms-logo.png" />
	  <None Remove="Assets\BmsMultiMon.png" />
	  <None Remove="Assets\CFG.png" />
	  <None Remove="Assets\Devices\F16 MFD 1.map.json" />
	  <None Remove="Assets\Devices\F16 MFD 1.png" />
	  <None Remove="Assets\Devices\F16 MFD 2.map.json" />
	  <None Remove="Assets\Devices\F16 MFD 2.png" />
	  <None Remove="Assets\Devices\Joystick - HOTAS Warthog.map.json" />
	  <None Remove="Assets\Devices\Joystick - HOTAS Warthog.png" />
	  <None Remove="Assets\Devices\Thrustmaster-Viper.png" />
	  <None Remove="Assets\DISX.png" />
	  <None Remove="Assets\EDIT.png" />
	  <None Remove="Assets\F4RADAR.png" />
	  <None Remove="Assets\F4WX.png" />
	  <None Remove="Assets\favicon.ico" />
	  <None Remove="Assets\icon-folder.png" />
	  <None Remove="Assets\icon-gear.png" />
	  <None Remove="Assets\icon-launch.png" />
	  <None Remove="Assets\icon-newspaper.png" />
	  <None Remove="Assets\icon-tools.png" />
	  <None Remove="Assets\IVCC.png" />
	  <None Remove="Assets\IVCS.png" />
	  <None Remove="Assets\MC.png" />
	  <None Remove="Assets\RTTClient64.png" />
	  <None Remove="Assets\RTTServer64.png" />
	  <None Remove="Assets\UPD.png" />
	  <None Remove="Assets\WC.png" />
	  <None Remove="Assets\WDP.png" />
	</ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Settings.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
    <Compile Update="Services\TheaterDiscoveryService.cs">
      <Generator>MSBuild:Compile</Generator>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Net.Http" Version="4.3.4" />
    <PackageReference Include="System.ServiceModel.Syndication" Version="10.0.3" />
    <PackageReference Include="Vortice.DirectInput" Version="2.4.2" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\bms-logo.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Devices\F16 MFD 1.map.json">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Devices\F16 MFD 1.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Devices\F16 MFD 2.map.json">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Devices\F16 MFD 2.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Devices\Joystick - HOTAS Warthog.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

	<ItemGroup>
		<Content Include="Stock\**\*.*">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
	</ItemGroup>

	<ItemGroup>
	  <Content Include="Assets\favicon.ico" />
	</ItemGroup>

	<ItemGroup>
	  <Resource Include="Assets\Devices\Joystick - HOTAS Warthog.map.json">
	    <CopyToOutputDirectory>Never</CopyToOutputDirectory>
	  </Resource>
	</ItemGroup>

</Project>
