//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FalconBMS.Launcher.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastInstall {
            get {
                return ((string)(this["LastInstall"]));
            }
            set {
                this["LastInstall"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ThirdPartyWdpExePath {
            get {
                return ((string)(this["ThirdPartyWdpExePath"]));
            }
            set {
                this["ThirdPartyWdpExePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ThirdPartyMissionCommanderExePath {
            get {
                return ((string)(this["ThirdPartyMissionCommanderExePath"]));
            }
            set {
                this["ThirdPartyMissionCommanderExePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ThirdPartyWeatherCommanderExePath {
            get {
                return ((string)(this["ThirdPartyWeatherCommanderExePath"]));
            }
            set {
                this["ThirdPartyWeatherCommanderExePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ThirdPartyF4WxExePath {
            get {
                return ((string)(this["ThirdPartyF4WxExePath"]));
            }
            set {
                this["ThirdPartyF4WxExePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ThirdPartyF4RadarExePath {
            get {
                return ((string)(this["ThirdPartyF4RadarExePath"]));
            }
            set {
                this["ThirdPartyF4RadarExePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CMD_ACMI {
            get {
                return ((bool)(this["CMD_ACMI"]));
            }
            set {
                this["CMD_ACMI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CMD_WINDOW {
            get {
                return ((bool)(this["CMD_WINDOW"]));
            }
            set {
                this["CMD_WINDOW"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CMD_NOMOVIE {
            get {
                return ((bool)(this["CMD_NOMOVIE"]));
            }
            set {
                this["CMD_NOMOVIE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CMD_EF {
            get {
                return ((bool)(this["CMD_EF"]));
            }
            set {
                this["CMD_EF"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CMD_MONO {
            get {
                return ((bool)(this["CMD_MONO"]));
            }
            set {
                this["CMD_MONO"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool VR_NoVR {
            get {
                return ((bool)(this["VR_NoVR"]));
            }
            set {
                this["VR_NoVR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool VR_SteamVR {
            get {
                return ((bool)(this["VR_SteamVR"]));
            }
            set {
                this["VR_SteamVR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool VR_OpenXR {
            get {
                return ((bool)(this["VR_OpenXR"]));
            }
            set {
                this["VR_OpenXR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Misc_bExportRTTTextures {
            get {
                return ((bool)(this["Misc_bExportRTTTextures"]));
            }
            set {
                this["Misc_bExportRTTTextures"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Misc_RLNWS {
            get {
                return ((bool)(this["Misc_RLNWS"]));
            }
            set {
                this["Misc_RLNWS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Misc_TrackIRZ {
            get {
                return ((bool)(this["Misc_TrackIRZ"]));
            }
            set {
                this["Misc_TrackIRZ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Misc_ExMouseLook {
            get {
                return ((bool)(this["Misc_ExMouseLook"]));
            }
            set {
                this["Misc_ExMouseLook"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Misc_NaturalHeadMovement {
            get {
                return ((bool)(this["Misc_NaturalHeadMovement"]));
            }
            set {
                this["Misc_NaturalHeadMovement"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Misc_PilotModel {
            get {
                return ((bool)(this["Misc_PilotModel"]));
            }
            set {
                this["Misc_PilotModel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Misc_SmartScalingOverride {
            get {
                return ((bool)(this["Misc_SmartScalingOverride"]));
            }
            set {
                this["Misc_SmartScalingOverride"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Auto")]
        public string LauncherThemeMode {
            get {
                return ((string)(this["LauncherThemeMode"]));
            }
            set {
                this["LauncherThemeMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ControlsDeviceColumnOrder {
            get {
                return ((string)(this["ControlsDeviceColumnOrder"]));
            }
            set {
                this["ControlsDeviceColumnOrder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LegacyImportPromptHandled {
            get {
                return ((bool)(this["LegacyImportPromptHandled"]));
            }
            set {
                this["LegacyImportPromptHandled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LaunchWithoutControlOverrides {
            get {
                return ((bool)(this["LaunchWithoutControlOverrides"]));
            }
            set {
                this["LaunchWithoutControlOverrides"] = value;
            }
        }
    }
}
